apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1 # Ensures the deployment matches pods with the label 'app: app1'.
  template:
    metadata:
      labels:
        app: app1 # Label applied to the pod template.
    spec:
      containers:
      - name: app1
        image: paulbouwer/hello-kubernetes:1.10 # Container image used to deploy the application.
        env:
        - name: MESSAGE
          value: "Hello from APP1." # Environment variable passed to the container. Reference: https://github.com/paulbouwer/hello-kubernetes/tree/main/src/app
        ports:
        - containerPort: 8080 # Port that the container inside the pod listens to for traffic.
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  type: ClusterIP # Exposes the service within the cluster using a cluster-internal IP.
  selector:
    app: app1 # The service targets pods with the label 'app: app1'.
  ports:
    - protocol: TCP
      port: 8081 # Port exposed by the service.
      targetPort: 8080 # Port on the pod that the service routes traffic to.
